inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*

Rails:
  Enabled: true

Documentation:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/LineLength:
  Max: 125

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

