# ##### The Rakefile
# `/Rakefile`
#

# *Generated by Rails*.
require_relative 'config/application'

# Record the start time and display a message a the start of the task.
# Then it yields the result to perform the task.
# At completion show a message with the time it took.
def timed
  start = Time.current
  puts 'start'

  yield

  puts "complete in #{Time.current - start}s"
end

# *Generated by Rails*.
Rails.application.load_tasks
