first_demo:
  title: Timing Rake rasks
  demo_url: /timing_rake
  summary: Where we explore creating a timing function that puts messages at the start and complete of a Rake task
  files:
    - Rakefile
    - lib/tasks/testing.rake
